trigger:
- main
- Develop
- erick-branch

pool:
  name: 'PipelinePaws' # Tu agente local en Windows

variables:
  azureServiceConnection: 'ConexionAzureAppService'
  webAppName: 'PawsHome'

stages:

# ==========================================
# ETAPA ÚNICA: INTEGRACIÓN CONTINUA (CI)
# ==========================================
- stage: Build
  displayName: 'Etapa de Compilación (CI)'
  jobs:
  - job: BuildJavaJob
    displayName: 'Compilar Spring Boot'
    steps:
    - task: Maven@4
      displayName: 'Maven clean package'
      inputs:
        mavenPomFile: 'pawshome/pom.xml'
        goals: 'clean package'
        options: '-DskipTests' 
        publishJUnitResults: false
        javaHomeOption: 'Path'
        jdkDirectory: 'C:\Program Files\Java\jdk-26.0.1'
        mavenVersionOption: 'Path'
        mavenDirectory: 'C:\Program Files\apache-maven-3.9.16'

    # MODIFICADO: Ahora solo busca y publica el archivo .jar ejecutable
    - task: PublishBuildArtifacts@1
      displayName: 'Guardar Artefacto Compilado (.jar)'
      inputs:
        PathtoPublish: '$(System.DefaultWorkingDirectory)/pawshome/target/pawshome-0.0.1-SNAPSHOT.jar' # Usa asterisco si el nombre cambia: '$(System.DefaultWorkingDirectory)/pawshome/target/*.jar'
        ArtifactName: 'pawshome-package'
        publishLocation: 'Container'