trigger:
- main
- Develop
- erick-branch

pool:
  name: 'PipelinePaws' # Tu agente local en Windows

variables:
  azureServiceConnection: 'ConexionAzureAppService'
  webAppName: 'PawsHome'

stages:

# ==========================================
# ETAPA 1: INTEGRACIÓN CONTINUA (CI)
# ==========================================
- stage: Build
  displayName: 'Etapa de Compilación (CI)'
  jobs:
  - job: BuildJavaJob
    displayName: 'Compilar Spring Boot'
    steps:
    - task: Maven@4
      displayName: 'Maven clean package'
      inputs:
        mavenPomFile: 'pawshome/pom.xml'
        goals: 'clean package'
        options: '-DskipTests' 
        publishJUnitResults: false
        javaHomeOption: 'Path'
        jdkDirectory: 'C:\Program Files\Java\jdk-26.0.1'
        mavenVersionOption: 'Path'
        mavenDirectory: 'C:\Program Files\apache-maven-3.9.16'

    - task: PublishBuildArtifacts@1
      displayName: 'Guardar Artefacto Compilado'
      inputs:
        PathtoPublish: '$(System.DefaultWorkingDirectory)/pawshome/target'
        ArtifactName: 'pawshome-package'
        publishLocation: 'Container'

# ==========================================
# ETAPA 2: DESPLIEGUE CONTINUO (CD) - CORREGIDA
# ==========================================
- stage: Deploy
  displayName: 'Etapa de Despliegue (CD)'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployAzureJob
    displayName: 'Desplegar a Azure App Service'
    # AQUÍ es donde debe ir para que active el botón de aprobación manual
    environment: 'Produccion' 
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            displayName: 'Descargar Artefacto'
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'pawshome-package'
              downloadPath: '$(System.ArtifactsDirectory)'

          - task: AzureWebApp@1
            displayName: 'Desplegar en Azure Web App'
            inputs:
              azureSubscription: '$(azureServiceConnection)'
              appType: 'webAppLinux'
              appName: '$(webAppName)'
              package: '$(System.ArtifactsDirectory)/pawshome-package/pawshome-*.war'
              
              # ESTA LÍNEA ES EL SECRETO para que no se quede colgado en bucle:
              deploymentMethod: 'zipDeploy'