trigger:
- main
- Develop
- erick-branch

pool:
  name: 'PipelinePaws' # Tu agente local en Windows

variables:
  azureServiceConnection: 'ConexionAzureAppService'
  webAppName: 'PawsHome'

stages:

# ==========================================
# ETAPA ÚNICA: INTEGRACIÓN CONTINUA (CI)
# ==========================================
- stage: Build
  displayName: 'Etapa de Compilación (CI)'
  jobs:
  - job: BuildJavaJob
    displayName: 'Compilar Spring Boot'
    steps:
    - task: Maven@4
      displayName: 'Maven clean package'
      inputs:
        mavenPomFile: 'pawshome/pom.xml'
        goals: 'clean package'
        options: '-DskipTests' 
        publishJUnitResults: false
        javaHomeOption: 'Path'
        jdkDirectory: 'C:\Program Files\Java\jdk-26.0.1'
        mavenVersionOption: 'Path'
        mavenDirectory: 'C:\Program Files\apache-maven-3.9.16'

    # PASO 1: Copiar solo el .jar a la carpeta temporal de artefactos
    - task: CopyFiles@2
      displayName: 'Filtrar y copiar archivo .jar'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)/pawshome/target'
        Contents: '*.jar'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    # PASO 2: Publicar el contenido de la carpeta temporal (donde ahora solo vive el .jar)
    - task: PublishBuildArtifacts@1
      displayName: 'Guardar Artefacto Compilado (.jar)'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'pawshome-package'
        publishLocation: 'Container'