spring.thymeleaf.cache=false

# SQL Server - Azure
spring.datasource.url=jdbc:sqlserver://pawshomesql.database.windows.net:1433;database=petconnect_db;encrypt=true;trustServerCertificate=false;loginTimeout=30;
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Azure Storage
azure.storage.connection-string=${AZURE_STORAGE_CONNECTION_STRING}
azure.storage.container-name=mascotas
